// Grabs the literal UserRole enum from your locally generated model definitions
import { prisma, shutdownPrisma, UserRole } from './client'; 

import { prisma, shutdownPrisma } from './client'; // Targets your secure pool client file
import { createHash } from 'crypto';

// Paste the exact UUID generated by your successful init.sh run here:
const TARGET_COMPANY_ID = "c792bbe1-e152-4fe5-adce-c9687dc4bff5";

/**
 * Utility helper to forge sequential SHA-256 chain anchors 
 * matching your CanonicalCryptoLedgerSchema format requirements
 */
function generateBlockLedger(index: number, prevHash: string = "0".repeat(64)) {
  const currentPayload = JSON.stringify({ index, timestamp: Date.now() });
// Update to call the single targeted method directly
const currentHash = createHash('sha256').update(currentPayload).digest('hex');

  return {
    previousEventHash: prevHash,
    currentEventHash: currentHash,
    sequenceNumber: index,
    verifiedAt: new Date().toISOString(),
  };
}

async function runMockSeeding() {
  console.log(`🚀 Starting data seeding layer for Company [${TARGET_COMPANY_ID}]...`);

  // ============================================
  // 1. SEED TEAM USERS (Maintains companyId lead)
  // ============================================
 // const adminUser = await prisma.user.create({
  //  data: {
   //   companyId: TARGET_COMPANY_ID,
   //   email: "ops.admin@fieldfsm.com",
   //   name: "Phil Operations",
   //   role: UserRole.admin, // Updated from plain string to exact generated Enum
//    },
  //});

  const leadTech = await prisma.user.create({
    data: {
      companyId: TARGET_COMPANY_ID,
      email: "tech.one@fieldfsm.com",
      name: "Alex Cross",
      role: UserRole.tech, // Updated from plain string to exact generated Enum
    },
  });

  console.log("✅ Identity records created safely behind multi-tenant fences.");

  // ============================================
  // 2. SEED HEAVY JSONB JOBS MATRIX
  // ============================================
  const initialJobLedger = generateBlockLedger(0);
  
  const hvacJob = await prisma.job.create({
    data: {
      companyId: TARGET_COMPANY_ID,
      contentHash: initialJobLedger.currentEventHash,
      previousHash: initialJobLedger.previousEventHash,
      createdBy: adminUser.id,
      
      // Pure un-modeled JSONB data container block evaluated by your GIN hot paths
      data: {
        status: "SCHEDULED",
        scheduledStart: new Date().toISOString(),
        scheduledEnd: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // +4 Hour Window
        baseMetadata: {
          title: "Emergency Compressor Changeout & System Diagnostics",
          assignedTechIds: [leadTech.id],
        },
        customFields: {
          customerName: "Acme Commercial Real Estate",
          serviceAddress: "742 Evergreen Terrace, Sector 7G",
          serviceDate: new Date().toISOString().split('T')[0],
        },
        // Embedded structural ledger representation inside the payload column
        ledger: initialJobLedger,
      } as any,
    },
  });

  console.log(`✅ Heavy JSONB Job record indexed successfully. ID: ${hvacJob.id}`);

  // ============================================
  // 3. SEED THE COMPLIANT CONTRACTS MATRIX
  // ============================================
  const contractLedger = generateBlockLedger(1, initialJobLedger.currentEventHash);
  
  // Note: Adjust the entity caller matching your exact pluralized model naming rule inside schema.prisma
  const serviceContract = await prisma.contract.create({
    data: {
      companyId: TARGET_COMPANY_ID,
      contentHash: contractLedger.currentEventHash,
      previousHash: contractLedger.previousEventHash,
      createdBy: adminUser.id,

      // Highly flexible data layout capturing the law book declarations
      data: {
        status: "ACTIVE",
        templateName: "standardService",
        legalTier: "company-standard",
        signingOrder: ["customer", "company"],
        sealedData: {
          totalAmount: 1450.00,
          workDescription: "Full primary dynamic heat pump diagnostic restoration asset validation.",
          customerName: "Acme Commercial Real Estate",
          serviceAddress: "742 Evergreen Terrace, Sector 7G",
        },
        ledger: contractLedger,
      } as any,
    },
  });

  console.log(`✅ Compliance Document Contract sealed successfully. ID: ${serviceContract.id}`);
  
  // ============================================
  // 4. GENERATE SYSTEM AUDIT TRAIL LOGS
  // ============================================
  await prisma.auditLog.create({
    data: {
      companyId: TARGET_COMPANY_ID,
      occurredAt: new Date(),
      actorId: adminUser.id,
      action: "TENANT_MOCK_DATA_HYDRATION",
      details: {
        seededEntities: ["users", "jobs", "contracts"],
        jobIdAnchor: hvacJob.id,
        contractIdAnchor: serviceContract.id,
      } as any,
    },
  });

  console.log("🎉 Complete transaction network seeding operation finalized.");
}

runMockSeeding()
  .catch((error) => {
    console.error("❌ Seeding Interruption Panic:", error);
    process.exit(1);
  })
  .finally(async () => {
    await shutdownPrisma(); // Clean connection release
  });
